### PR TITLE
`String` support for JIT

### PR DESCRIPTION
**Pull request by marzipankaiser**

### CODE REVIEW

**Comment by jfrech** [comment]
I fear you branched off of very unstable work.

**Comment by marzipankaiser** [comment]
That's OK, I can probably just rebase it and change some baisc stuff. But thanks for the warning

**Comment by marzipankaiser** [comment]
Is there already a stable one?

**Comment by b-studios** [comment]
@marzipankaiser @jfrech Is the machine representation stable enough, though?

**Comment by jfrech** [comment]
@marzipankaiser @b-studios Yes, machine is stable: https://github.com/effekt-lang/effekt/pull/142/files#diff-1fe3ea2b373d50d05402e8d2628884f276ba14b9ce01acc4d04cc52ac977487dR145

**Pull request merged**
