### PR TITLE
Add support for Holes to machine and llvm

### PR DESCRIPTION
**Pull request by marzipankaiser**
When executed, a hole will print a generic error message and exit with exit code 1.

### CODE REVIEW

**Comment by b-studios** [comment]
Can we also desugar holes into a primitive call instead of a separate syntax object?

**Comment by marzipankaiser** [comment]
You mean in machine already? Or even earlier?

**Comment by b-studios** [comment]
Right now I was thinking of Machine; but maybe even as early as core?

**Comment by marzipankaiser** [comment]
Then, we would have to somehow get at the symbol of the builtin. 🤔
Also, this might make it harder to implement some backend-specific behaviours for holes (e.g. if we would ever compile to a target that has support for holes, it would be nice if we could just use that).

I don't know what's the better solution, I think that - for now - this is more consistent with the other parts (core, lifted), though.

**Comment by b-studios** [comment]
Ok, I don't have a strong preference since it is easily changed.

**Comment by marzipankaiser** [comment]
Requested review mostly fyi. Will now merge.

**Pull request merged**
