### PR TITLE
Try to improve resolution by adding a bit context

### PR DESCRIPTION
**Pull request by b-studios**
This is an attempt to improve on #670. However, there are some trade-offs as can be seen in the modified test.

Another thing is that the error messages are really bad now if something cannot be found.

### CODE REVIEW

**Comment by b-studios** [comment]
Currently, there is an issue where in `bytearray` we have

```
def resize(source: ByteArray, size: Int): ByteArray = {
  val target = allocate(size)
  val n = min(source.size, target.size)
  def go(i: Int): ByteArray =
    if (i < n) {
      target.unsafeSet(i, source.unsafeGet(i))
      go(i + 1)
    } else {
      target
    }
  go(0)
}
```

There the parameter `size` (a value) shadows the selector `.size`.

**Comment by jiribenes** [comment]
Would specialising on arity help there? If there's something like `foo.bar`, then perhaps it's more likely to be field access than a method/UFCS'd function?

**Comment by b-studios** [comment]
In 4982b9c, I was able to improve the precision a bit further and revert some changes to tests. 

The strategy is now to first try the respective function / operation lookup and if this fails **completely** then also try the other... you never know ;)

**Comment by b-studios** [comment]
Maybe the special casing of error messages is useless, but I'll merge this so that we can have this in the next release.

**Pull request merged**
