### PR TITLE
multi-line `extern` definitions ; LLVM stdlib

### PR DESCRIPTION
**Pull request by jfrech**

### CODE REVIEW

**Review by b-studios — APPROVED** [review]
~LGTM~

Wait the changes look good to me (without looking too much into the regex). However, the tests still fail.

@jfrech Please don't merge until the tests run through.

**Review by b-studios — CHANGES_REQUESTED** [review]
Tests fail.

**Comment by jfrech** [comment]
@b-studios Yes, a lot of tests fail. I suspect a lexer ordering issue, yet could not come up with a fix.

**Comment by b-studios** [comment]
The failure of the `anf.md` test is strange. It does work on my machine.

**Review by b-studios — APPROVED** [review]

**Comment by b-studios** [comment]
@jfrech Could you resolve the merge conflicts? Then we are ready to merge this PR.

**Comment by jfrech** [comment]
@b-studios I would, yet am underprivileged.

**Pull request merged**
