### PR TITLE
PolymorphismBoxing for Any/Nothing

### PR DESCRIPTION
**Pull request by marzipankaiser**

### CODE REVIEW

**Comment by marzipankaiser** [comment]
#453 still occurs unchanged with this.

**Comment by marzipankaiser** [comment]
@phischu Which example was it that should be fixed by this? (I lost track of the failing llvm examples)

**Comment by b-studios** [comment]
@marzipankaiser thanks for the quick fix. Is there a test that would fail before and now passes?

**Comment by marzipankaiser** [comment]
The generated core with hacked-in type info for #453 is:
```
def main322() =
  def loop324() =
    let _407 = println18("!")
    
    loop324();
  let x326 = run {let tmp339408 = run {loop324()}
  
  <>} ///  <- here, we return Nothing, so x326 will be bound with type Nothing
  
  infixAdd32(x326:Int233, 1)
```
Here, `x326` will *not* be unboxed (although it is Nothing), since we only look for type mismatches *locally*, i.e. we do not track an environment of the types of bound variables. However, to detect at the use site of `x` that this is not an int, we would need to. I wonder, maybe it is possible to construct this with "normal" (parametric polymorphism-related) boxing :thinking:

**Comment by marzipankaiser** [comment]
> @marzipankaiser thanks for the quick fix. Is there a test that would fail before and now passes?

I have not found one yet. But I'm open for suggestions.

**Comment by phischu** [comment]
I believe the cleanest solution for this and transitively for #453 is to add an explicit upcast expression to Core.

**Comment by b-studios** [comment]
Do we need explicit upcasts or is it enough to annotate `val` bindings with the annotated type? One thing that concerns me about explicit upcasts is how they will interact with optimizations (they need to be able to see through them, but at the same time keep them if necessary).

**Pull request merged**
